### ISSUE TITLE
kombat theater menu error in mortal kombat 4

### ISSUE THREAD

**Issue by Reideldm** [notaz/pcsx_rearmed#304] opened 2023-09-07 06:02 UTC
in mortal kombat 4 in the kombat theater menu when you highlight a character and press l1 to see the bio video the emulator crashes

**Comment by notaz** [comment] 2023-09-07 20:59
This was fixed more than a month ago, you need to update.

Duplicate of libretro/pcsx_rearmed#740

**Closed by notaz** 2023-09-07 20:59 UTC
