### ISSUE TITLE
[Bug] Crash Bash (Europe) Can't see the in game battle menu

### ISSUE THREAD

**Issue by Darknior** [notaz/pcsx_rearmed#95] opened 2017-09-10 22:36 UTC
When you play on PI 3 with Retropie 4.2 and the **last PCSX Rearmed from source** code, all the games are working perfectly. But some time we have some little bugs like this one that make  the game harder to use.

With **Carsh Bash** all is fine but in battle mode, when you press **START** to see the in game menu to leave the match or change arena, you **can't see any text**, only listen the sound when moving in the menu.
Is it possible to correct this issue ?

![20170911_000109_hdr](https://user-images.githubusercontent.com/3703317/30253619-36b631d8-9689-11e7-8e1b-a863a2796384.jpg)

https://github.com/libretro/pcsx_rearmed/issues/140

**Comment by dankcushions** [comment] 2017-09-10 22:46
stop logging duel issues in both the libretro and standalone core. if the issue is in standalone and libretro fork, log it in standalone only. if it's only in libretro fork, log it in libretro fork only. raising two issues is always wrong.

**Comment by Darknior** [comment] 2017-09-10 22:49
Ok thanks, sorry, i do it because i see some other doing it.
I understand i can log them, but not really understand how to do it because the **Reference issue** button only show me issue here and not in the other Git :(
Can you explain me please ?

**Comment by dankcushions** [comment] 2017-09-10 23:01
yes, @nemo93 is doing the same bad thing also. stop!

like i said, you should only ever create one issue for a single problem, rather than duplicate it across every fork, so i don't know why you're talking about referencing issues.

please take these discussions to the retropie forum. git is not a forum.

**Comment by notaz** [comment] 2023-09-29 20:46
IIRC I fixed it a while ago, closing.

**Closed by notaz** 2023-09-29 20:46 UTC
