### ISSUE TITLE
Dynarec only bugs/crashes

### ISSUE THREAD

**Issue by gameblabla** [notaz/pcsx_rearmed#213] opened 2021-09-04 11:57 UTC
I'm making a list of games that run through the interpreter but not through the ARM dynarec.
So far, i only know a few of them but let me know.
For the test machine, i'm using the Funkey-S.

- WWF In the House
This crashes the emulator. GDB unfortunately isn't very helpful and only points towards translation_cache()
```sh
Thread 1 "pcsx" received signal SIGILL, Illegal instruction.
0x005404e4 in translation_cache ()
#0  0x005404e4 in translation_cache ()
#1  0x00000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
A debugging session is active.

	Inferior 1 [process 12929] will be killed.

```

- iS - Internal Section
Black screen instead of booting normally. Unlike WWF, this seems to point towards an inaccuracy or oversight in the ARM dynarec instead. I have heard the libretro version also has the same issue. (unless you use lightrec, in which case it should work)

- Psybadek 
Crashes on ARM.

- Star Wars Episode I: Jedi Power Battles
Crashes some time after. SMC Checks should be turned off for the game to be playable.

- Any games that rely on icache emulation.
This includes F1 2001 (car will go crazy ingame otherwise), F1 Arcade (black screen after loading screen), F1 99 (crashes after loading screen) and EA's F1 2000 (freezes after disclaimer screen). The interpreter has an icache emulation (thanks to my PRs) and they are playable over there.

**Comment by notaz** [comment] 2021-11-16 23:52
These should be fixed now (or rather hacked-around for Internal Section).

"WWF In Your House" shows garbage backgrounds, but that also happens with the interpreter. If it worked before, maybe a cdrom regression?

**Comment by gameblabla** [comment] 2021-11-17 12:59
> 
> 
> These should be fixed now (or rather hacked-around for Internal Section).
> 
> "WWF In Your House" shows garbage backgrounds, but that also happens with the interpreter. If it worked before, maybe a cdrom regression?
I do not think it is a CDROM regression issue as i have merged my CDROM changes to PCSX-Redux and they don't have the issue. For now i'm only suspecting an issue in gpulib or the fact the game relies on delayed loads. (I know Threads of Fate will glitch up and crash without those, as mentionned in mednafen's doc. I made an attempt for the interpreter here :
https://github.com/gameblabla/pcsx_rearmed/tree/delayed_loads
But i couldn't get it to work properly over interpreter.

I have added a few other games that are known to have issues over the dynarec (including icache emulation. I don't think you will want to work on it but i'm adding it for reference).
Thank you for your work

**Comment by notaz** [comment] 2021-11-23 00:04
Psybadek triggered an alignment issue in color space conversion (so not even a dynarec issue), an easy fix.

Star Wars triggered a pretty nasty dynarec bug that never triggered on pandora because of it's memory layout, so I never fixed it when I actively worked on the emu years ago. It was likely to crash any game that loads more code, but 
Star Wars was a lot faster to trigger it. I think it's good now.

I though a bit about icache, it can be done but it's just too much work. I'll see if there is some easier hack instead.

If you have anything else it would be good to know while I still remember roughly how everything works, when some months pass again it will be very difficult to get back to it. Especially when current mobile hardware is fast enough to run everything without dynarec anyway...

**Comment by notaz** [comment] 2021-11-24 21:08
Pushed a hack for the F1 games which allows them to start the race at least. No idea if it's enough to be able to play them to completion, chances are it is.

**Comment by notaz** [comment] 2022-04-08 21:32
I think all these games work by now, closing.

**Closed by notaz** 2022-04-08 21:32 UTC
