### ISSUE TITLE
This is Football 2 - Black screen

### ISSUE THREAD

**Issue by ransom1122** [notaz/pcsx_rearmed#141] opened 2019-09-08 21:43 UTC
Hi.

I am having problems with this game, it black screens after the intro? I have tried so many different setting configs in options and in video, I have the correct BIOS files matching the md5 on your website and the game still fails to play?

The game works in beetle core, but not in psxrearmed?

Does anyone know why?

**Comment by gameblabla** [comment] 2021-08-25 12:53
The lockup issue is caused by an oversight in the Reset CDROM command code and further compounded by the confusion between the init and reset commands, hence why they couldn't investigate it the lockup issue.
This is fixed by setting cdr.Mode to 0x20 in CdlReset.
This is done as such here :
https://github.com/notaz/pcsx_rearmed/pull/205

**Closed** 2023-09-29 21:44 UTC
