### ISSUE TITLE
Duke Nukem: Land of the Babes (USA), weird graphical glitch while underwater.

### ISSUE THREAD

**Issue by valter12437** [notaz/pcsx_rearmed#289] opened 2023-02-02 22:03 UTC
This happens everytime you go in any underwater area in the game:
![Duke Nukem - Land of the Babes (USA)-230202-184349](https://user-images.githubusercontent.com/82282361/216458879-b524df23-6ab9-4521-b231-a5ca4be71067.png)
I'm using PCSX-ReARMed (r23l aced3eb) on Windows 10 Home trough RetroArch.

**Comment by pcercuei** [comment] 2023-03-06 13:08
@valter12437 Do you have a savestate you could share to reproduce the problem?

**Comment by valter12437** [comment] 2023-03-06 13:48
@pcercuei sure, here it goes. Just load the state and jump into the pool. Alternatively, select the training stage, go to the pool area and jump in.

[Duke Nukem - Land of the Babes (USA).zip](https://github.com/notaz/pcsx_rearmed/files/10898826/Duke.Nukem.-.Land.of.the.Babes.USA.zip)

**Comment by m4xw** [comment] 2023-04-12 18:20
Took me 1.5 days but i tracked it to this OP https://github.com/libretro/pcsx_rearmed/blob/master/plugins/gpu_unai/gpulib_if.cpp#L748
Not sure why yet but stubbing it fixes it for unai, will investigate further tomorrow, up for ideas if anyone has

**Comment by m4xw** [comment] 2023-04-12 18:20
On another note i also fixed unit tests on some GTE ops but guess will handle that seperately since it didnt turn out to be that

**Comment by m4xw** [comment] 2023-04-12 21:12
![grafik](https://user-images.githubusercontent.com/13141469/231585263-240d5630-17b3-4d21-a0ad-65e39719385b.png)
This appears to fix it, might be a off-by-one in all gpu plugins?
AFAIK this effect works on hardware, but this seems like a weird oversight if u ask me, at least silently discarding it doesnt do the trick in this case
![grafik](https://user-images.githubusercontent.com/13141469/231585598-86b55564-a5f2-4e50-a50a-db7fc2a07afd.png)
It does set those params as well and sends data with those locations in mind so that would check out.
peops had same issue as unai here but neon gpu was more funky, I hope you know whats going on here, @notaz
Also if u look at the original image theres some shenanigans at the right edge etc so thats also reaffirming

**Comment by m4xw** [comment] 2023-04-12 21:19
Double checking against using 511/1023 and using the top codepath with >= for them still is broken, so appears to me this needs indeed 1024/512
![grafik](https://user-images.githubusercontent.com/13141469/231587523-0d8d5509-fc08-4250-ad7b-4de5f6921302.png)

**Comment by pcercuei** [comment] 2023-04-12 21:31
Using 512/1024 does make absolutely zero sense, though.

**Comment by m4xw** [comment] 2023-04-12 21:38
As far i can tell from the games code it looks to be doing some offscreen vertices

**Comment by pcercuei** [comment] 2023-04-12 21:43
What do you get if you print x0 / y0 / x1 / y1 / w0 / h0?
Is that your screenshot with the "set drawing area" messages?

**Comment by m4xw** [comment] 2023-04-12 21:44
[The screenshot was the](https://github.com/libretro/pcsx_rearmed/blob/master/plugins/gpu_unai/gpulib_if.cpp#L363-L381)

**Comment by m4xw** [comment] 2023-04-12 21:47
Here i just dumped the umasked vals for one frame:
x0: 512, y0: 2, x1: 511, y1: 2, w0: 512, h0: 2
x0: 512, y0: 4, x1: 511, y1: 4, w0: 512, h0: 2
x0: 512, y0: 6, x1: 511, y1: 6, w0: 512, h0: 2
x0: 512, y0: 8, x1: 511, y1: 8, w0: 512, h0: 2
x0: 512, y0: 10, x1: 511, y1: 10, w0: 512, h0: 2
x0: 512, y0: 12, x1: 510, y1: 12, w0: 512, h0: 2
x0: 512, y0: 14, x1: 510, y1: 14, w0: 512, h0: 2
x0: 512, y0: 16, x1: 510, y1: 16, w0: 512, h0: 2
x0: 512, y0: 18, x1: 510, y1: 18, w0: 512, h0: 2
x0: 512, y0: 20, x1: 510, y1: 20, w0: 512, h0: 2
x0: 512, y0: 22, x1: 510, y1: 22, w0: 512, h0: 2
x0: 512, y0: 24, x1: 509, y1: 24, w0: 512, h0: 2
x0: 512, y0: 26, x1: 509, y1: 26, w0: 512, h0: 2
x0: 512, y0: 28, x1: 509, y1: 28, w0: 512, h0: 2
x0: 512, y0: 30, x1: 509, y1: 30, w0: 512, h0: 2
x0: 512, y0: 32, x1: 509, y1: 32, w0: 512, h0: 2
x0: 512, y0: 34, x1: 509, y1: 34, w0: 512, h0: 2
x0: 512, y0: 36, x1: 508, y1: 36, w0: 512, h0: 2
x0: 512, y0: 38, x1: 508, y1: 38, w0: 512, h0: 2
x0: 512, y0: 40, x1: 508, y1: 40, w0: 512, h0: 2
x0: 512, y0: 42, x1: 508, y1: 42, w0: 512, h0: 2
x0: 512, y0: 44, x1: 508, y1: 44, w0: 512, h0: 2
x0: 512, y0: 46, x1: 508, y1: 46, w0: 512, h0: 2
x0: 512, y0: 48, x1: 508, y1: 48, w0: 512, h0: 2
x0: 512, y0: 50, x1: 508, y1: 50, w0: 512, h0: 2
x0: 512, y0: 52, x1: 508, y1: 52, w0: 512, h0: 2
x0: 512, y0: 54, x1: 508, y1: 54, w0: 512, h0: 2
x0: 512, y0: 56, x1: 508, y1: 56, w0: 512, h0: 2
x0: 512, y0: 58, x1: 508, y1: 58, w0: 512, h0: 2
x0: 512, y0: 60, x1: 508, y1: 60, w0: 512, h0: 2
x0: 512, y0: 62, x1: 508, y1: 62, w0: 512, h0: 2
x0: 512, y0: 64, x1: 508, y1: 64, w0: 512, h0: 2
x0: 512, y0: 66, x1: 508, y1: 66, w0: 512, h0: 2
x0: 512, y0: 68, x1: 508, y1: 68, w0: 512, h0: 2
x0: 512, y0: 70, x1: 508, y1: 70, w0: 512, h0: 2
x0: 512, y0: 72, x1: 508, y1: 72, w0: 512, h0: 2
x0: 512, y0: 74, x1: 508, y1: 74, w0: 512, h0: 2
x0: 512, y0: 76, x1: 508, y1: 76, w0: 512, h0: 2
x0: 512, y0: 78, x1: 508, y1: 78, w0: 512, h0: 2
x0: 512, y0: 80, x1: 508, y1: 80, w0: 512, h0: 2
x0: 512, y0: 82, x1: 508, y1: 82, w0: 512, h0: 2
x0: 512, y0: 84, x1: 508, y1: 84, w0: 512, h0: 2
x0: 512, y0: 86, x1: 508, y1: 86, w0: 512, h0: 2
x0: 512, y0: 88, x1: 508, y1: 88, w0: 512, h0: 2
x0: 512, y0: 90, x1: 508, y1: 90, w0: 512, h0: 2
x0: 512, y0: 92, x1: 508, y1: 92, w0: 512, h0: 2
x0: 512, y0: 94, x1: 508, y1: 94, w0: 512, h0: 2
x0: 512, y0: 96, x1: 509, y1: 96, w0: 512, h0: 2
x0: 512, y0: 98, x1: 509, y1: 98, w0: 512, h0: 2
x0: 512, y0: 100, x1: 509, y1: 100, w0: 512, h0: 2
x0: 512, y0: 102, x1: 509, y1: 102, w0: 512, h0: 2
x0: 512, y0: 104, x1: 509, y1: 104, w0: 512, h0: 2
x0: 512, y0: 106, x1: 509, y1: 106, w0: 512, h0: 2
x0: 512, y0: 108, x1: 510, y1: 108, w0: 512, h0: 2
x0: 512, y0: 110, x1: 510, y1: 110, w0: 512, h0: 2
x0: 512, y0: 112, x1: 510, y1: 112, w0: 512, h0: 2
x0: 512, y0: 114, x1: 510, y1: 114, w0: 512, h0: 2
x0: 512, y0: 116, x1: 510, y1: 116, w0: 512, h0: 2
x0: 512, y0: 118, x1: 510, y1: 118, w0: 512, h0: 2
x0: 512, y0: 120, x1: 511, y1: 120, w0: 512, h0: 2
x0: 512, y0: 122, x1: 511, y1: 122, w0: 512, h0: 2
x0: 512, y0: 124, x1: 511, y1: 124, w0: 512, h0: 2
x0: 512, y0: 126, x1: 511, y1: 126, w0: 512, h0: 2
x0: 512, y0: 128, x1: 511, y1: 128, w0: 512, h0: 2
x0: 512, y0: 140, x1: 513, y1: 140, w0: 512, h0: 2
x0: 512, y0: 142, x1: 513, y1: 142, w0: 512, h0: 2
x0: 512, y0: 144, x1: 513, y1: 144, w0: 512, h0: 2
x0: 512, y0: 146, x1: 513, y1: 146, w0: 512, h0: 2
x0: 512, y0: 148, x1: 513, y1: 148, w0: 512, h0: 2
x0: 512, y0: 150, x1: 513, y1: 150, w0: 512, h0: 2
x0: 512, y0: 152, x1: 514, y1: 152, w0: 512, h0: 2
x0: 512, y0: 154, x1: 514, y1: 154, w0: 512, h0: 2
x0: 512, y0: 156, x1: 514, y1: 156, w0: 512, h0: 2
x0: 512, y0: 158, x1: 514, y1: 158, w0: 512, h0: 2
x0: 512, y0: 160, x1: 514, y1: 160, w0: 512, h0: 2
x0: 512, y0: 162, x1: 514, y1: 162, w0: 512, h0: 2
x0: 512, y0: 164, x1: 515, y1: 164, w0: 512, h0: 2
x0: 512, y0: 166, x1: 515, y1: 166, w0: 512, h0: 2
x0: 512, y0: 168, x1: 515, y1: 168, w0: 512, h0: 2
x0: 512, y0: 170, x1: 515, y1: 170, w0: 512, h0: 2
x0: 512, y0: 172, x1: 515, y1: 172, w0: 512, h0: 2
x0: 512, y0: 174, x1: 515, y1: 174, w0: 512, h0: 2
x0: 512, y0: 176, x1: 515, y1: 176, w0: 512, h0: 2
x0: 512, y0: 178, x1: 515, y1: 178, w0: 512, h0: 2
x0: 512, y0: 180, x1: 515, y1: 180, w0: 512, h0: 2
x0: 512, y0: 182, x1: 515, y1: 182, w0: 512, h0: 2
x0: 512, y0: 184, x1: 515, y1: 184, w0: 512, h0: 2
x0: 512, y0: 186, x1: 515, y1: 186, w0: 512, h0: 2
x0: 512, y0: 188, x1: 515, y1: 188, w0: 512, h0: 2
x0: 512, y0: 190, x1: 515, y1: 190, w0: 512, h0: 2
x0: 512, y0: 192, x1: 515, y1: 192, w0: 512, h0: 2
x0: 512, y0: 194, x1: 515, y1: 194, w0: 512, h0: 2
x0: 512, y0: 196, x1: 515, y1: 196, w0: 512, h0: 2
x0: 512, y0: 198, x1: 515, y1: 198, w0: 512, h0: 2
x0: 512, y0: 200, x1: 515, y1: 200, w0: 512, h0: 2
x0: 512, y0: 202, x1: 515, y1: 202, w0: 512, h0: 2
x0: 512, y0: 204, x1: 515, y1: 204, w0: 512, h0: 2
x0: 512, y0: 206, x1: 515, y1: 206, w0: 512, h0: 2
x0: 512, y0: 208, x1: 515, y1: 208, w0: 512, h0: 2
x0: 512, y0: 210, x1: 515, y1: 210, w0: 512, h0: 2
x0: 512, y0: 212, x1: 515, y1: 212, w0: 512, h0: 2
x0: 512, y0: 214, x1: 515, y1: 214, w0: 512, h0: 2
x0: 512, y0: 216, x1: 515, y1: 216, w0: 512, h0: 2
x0: 512, y0: 218, x1: 515, y1: 218, w0: 512, h0: 2
x0: 512, y0: 220, x1: 515, y1: 220, w0: 512, h0: 2
x0: 512, y0: 222, x1: 515, y1: 222, w0: 512, h0: 2
x0: 512, y0: 224, x1: 514, y1: 224, w0: 512, h0: 2
x0: 512, y0: 226, x1: 514, y1: 226, w0: 512, h0: 2
x0: 512, y0: 228, x1: 514, y1: 228, w0: 512, h0: 2
x0: 512, y0: 230, x1: 514, y1: 230, w0: 512, h0: 2
x0: 512, y0: 232, x1: 514, y1: 232, w0: 512, h0: 2
x0: 512, y0: 234, x1: 514, y1: 234, w0: 512, h0: 2
x0: 512, y0: 236, x1: 513, y1: 236, w0: 512, h0: 2
x0: 512, y0: 238, x1: 513, y1: 238, w0: 512, h0: 2

**Comment by m4xw** [comment] 2023-04-12 21:49
Side Note: When i open the menu ingame (and it doesnt apply the caustic effect underwater) then it never invokes moveImage to begin with so the issue never appears

**Comment by m4xw** [comment] 2023-04-12 21:59
Btw i could give some further insight if you contact me on discord ask i cant say too much on github due to circumstances  m4xw#1560

**Comment by pcercuei** [comment] 2023-04-12 22:03
The values look OK. I think it's just the algorithm that does not work properly with these values. It looks like the game tries to move lines of the framebuffer left and right to give it a wobble "underwater" effect. In the case where x1 > x0, the algorithm will actually copy pixel N[i] to N[i + n], which only works if you copy less than n pixels.

**Comment by m4xw** [comment] 2023-04-12 22:04
The wobble effect doesnt happen with my change as far i can tell (checking over RDP rn and its a blurry mess)

**Comment by m4xw** [comment] 2023-04-12 22:05
I do have some indication this might be abusing either a bug or a edge case to get the effect without the artifact

**Comment by Squall-Leonhart** [comment] 2023-04-13 02:33
@Nucleoprotein do you have an idea here?

**Comment by pcercuei** [comment] 2023-04-13 17:16
The bug seems to occur in all GPU plugins (neon, peops, unai).

The problem is that the VRAM->VRAM copy does not handle the case where the source and destination overlap.

One workaround in Unai is to copy the source to an intermediate buffer first:

```patch
diff --git a/plugins/gpu_unai/gpu_raster_image.h b/plugins/gpu_unai/gpu_raster_image.h
index 0c82aa97..31ad2692 100644
--- a/plugins/gpu_unai/gpu_raster_image.h
+++ b/plugins/gpu_unai/gpu_raster_image.h
@@ -81,14 +81,19 @@ INLINE void gpuMoveImage(void)
        if( (x0==x1) && (y0==y1) ) return;
        if ((w0<=0) || (h0<=0)) return;
        
-       if (((y0+h0)>512)||((x0+w0)>1024)||((y1+h0)>512)||((x1+w0)>1024))
+       if (1)
        {
                u16 *psxVuw=GPU_FrameBuffer;
                s32 i,j;
-           for(j=0;j<h0;j++)
-                for(i=0;i<w0;i++)
-                 psxVuw [(1024*((y1+j)&511))+((x1+i)&0x3ff)]=
-                  psxVuw[(1024*((y0+j)&511))+((x0+i)&0x3ff)];
+               u16 *tmp = (u16 *)alloca(sizeof(*tmp) * w0 * h0);
+
+               for (j = 0; j < h0; j++)
+                       for (i = 0; i < w0; i++)
+                               tmp[j * w0 + i] = psxVuw[1024*((y0+j)&511)+((x0+i)&0x3ff)];
+
+               for (j = 0; j < h0; j++)
+                       for (i = 0; i < w0; i++)
+                               psxVuw[1024*((y1+j)&511)+((x1+i)&0x3ff)] = tmp[j * w0 + i];
        }
        else if ((x0&1)||(x1&1))
        {
```

Of course this isn't very optimized, but at least it works.

**Comment by Squall-Leonhart** [comment] 2023-04-13 18:31
> The bug seems to occur in all GPU plugins (neon, peops, unai).

It doesn't occur in [Kazzuya Soft](https://dl.emulator-zone.com/download.php/emulators/psx/plugins/graphics/Kazzuya/gpuKazSoft18a.zip)

**Comment by notaz** [comment] 2023-10-02 21:42
This should be fixed now. Many thanks to everyone who helped debugging this and posted info.

**Closed by notaz** 2023-10-02 21:42 UTC

**Comment by pcercuei** [comment] 2023-10-06 13:31
@notaz, your commit 36da9c1305 breaks Looney Tunes Sheep Raider. When trying to enter the very first level, the loading screen will never complete. I have no idea how it can be related; but reverting this commit on master fixes it.

**Comment by m4xw** [comment] 2023-10-06 13:36
Also I got told unai broke as well

**Comment by pcercuei** [comment] 2023-10-06 17:30
@m4xw broke how? We're using Unai and I didn't notice breakages related to this commit.

**Comment by notaz** [comment] 2023-10-08 15:34
> When trying to enter the very first level, the loading screen will never complete

Well it actually completed but it wasn't visible because I forgot to mark the fb for flipping. It should be fixed now.

**Comment by m4xw** [comment] 2023-10-09 10:03
Duke TTK:
![image](https://github.com/notaz/pcsx_rearmed/assets/13141469/56c11d5f-3fdd-4693-b20f-351bcf3f8efa)

https://github.com/notaz/pcsx_rearmed/assets/13141469/6e0182cd-ec2e-4016-bb2b-62b933ebd810

**Comment by m4xw** [comment] 2023-10-09 10:03
Dunno whats up with the video so heres another upload https://m4xw.net/nextcloud/index.php/s/akMMf2diqQYsZ7M

**Comment by Ploggy** [comment] 2023-10-09 11:40
The flickering is to do with Unai's Dithering, turn it off and the flickering will stop.
