### ISSUE TITLE
[Audio] Legend of Mana audio sync issue in FMV

### ISSUE THREAD

**Issue by ghost** [notaz/pcsx_rearmed#126] opened 2019-03-08 15:07 UTC
During Legend of Mana intro fmv (or any of its fmv), audio between left and right goes out of sync

how to reproduce:
just load legend of mana and let the game play itself. the fmv before the prelude should have more noticeable audio desync since it has vocals.

tested on linux using latest commit ecade89

original post from here: and i tested on standalone and has the same audio problem:
https://github.com/libretro/pcsx_rearmed/issues/110

2019-03-15 UPDATE:
b1ba085: this is the last better sounding commit  at least if tested on libretro port. the standalone, compiled on linux already has only right audio channel working at times during FMV and is stuttering alot.

**Comment by retro-wertz** [comment] 2019-03-14 18:47
Hi i managed to bisect this. and figured that this is where audio issues started...

this is the last better sounding commit : https://github.com/notaz/pcsx_rearmed/commit/b1ba08510c208685fda8a0a2d0e2b72d98db23b1

commits after that has either crashes libretro port, or already has audio problems in the standalone (only right channels has audio, then after awhile audio breaks up during FMV intro or right after placing mailbox thing)

this issue can be found between release 20 and release 19

**Comment by notaz** [comment] 2019-03-18 00:42
Thanks for finding this is a regression. The real bad commit is 650adfd2da779ba8855623362c2900583e22931e which was a complete audio synchronization rewrite, not an easy thing to fix.

**Comment by retro-wertz** [comment] 2019-03-23 11:17
hi thanks for the confirmation. i did found out just awhile ago that changing BIAS to 6 fixes the audio desync (fixes dysync though there are audio stutters but at least it sounded better and we are making progress :D)

https://github.com/notaz/pcsx_rearmed/blob/master/libpcsxcore/psxcommon.h#L155

i noticed this on pcsx4all...

**Comment by maxsteiner71** [comment] 2019-04-03 06:40
Same problem in Parasite Eve. In police department audio desync.

**Comment by retrowertz** [comment] 2022-11-04 04:08
with the latest changes to the spu on libretro's fork, the audio desync on this particular game has been finally fixed. thanks for doing so.

i assume those commits are already included in this master branch, if so, then feel free to close this issue since i since lost this account.

thanks again.

**Closed** 2022-11-05 21:29 UTC
