### ISSUE TITLE
[BUG] Diablo - Music bug 

### ISSUE THREAD

**Issue by UristUriston** [notaz/pcsx_rearmed#121] opened 2019-03-01 12:55 UTC
The music in DIABLO works perfectly. Until you press start or interact with somebody. After that it is muted until the track loops or you press start again - When you press start to make the music run again it only runs for a few seconds and cuts out again at random. This is no sound/music stuttering but a unique bug.  

Tested on Retroarch NES Classic Mini and also on Raspberry Pi 3 B+ Retropie 4.3 with different Roms. 
Google search reveals that this bug might be a few years old. 

Might be unrelated but on PSX2PSP there was a slighlty similar bug in which the game would press start (pause) on random. The timing reminded me of this weird bug.  

A shame, the best co-op PSX game and a timeless classic.

**Comment by gingerbeardman** [comment] 2019-03-02 22:51
This could be the same as #122

**Comment by nkotzias** [comment] 2019-03-03 21:23
I have made a [fork](https://github.com/nkotzias/pcsx_rearmed) which seems to fix the issue (it's actually more of a hack than a fix). The commit message explains a bit more about why the music stops playing.

**Comment by UristUriston** [comment] 2019-03-03 21:36
Thanks for looking into it and I am absolutely amazed that you figured out what´s going and found a quick fix. Thanks for that! 
Uhm.. where does it go from here? Will this fix trickle down to the dumb standard users like me eventually?

**Comment by UristUriston** [comment] 2019-03-05 15:11
Uhm... I was actually a bit serious.. I just submitted a bug report but actually have no idea how things like that work. Is there anything I can do to help.. besides learning to code which would take a few years?

All I want to do is play diablo on my nes mini :laughing:

**Comment by gingerbeardman** [comment] 2019-03-05 15:30
It's... complicated. The key is to be patient. 

The change has been described as a hack, so ideally it needs to be tested to see if it breaks any other games. 

If all is OK then eventually the change will be picked up by libretro "downstream" and it will make it into a nightly, and sometime later a stable release version. After either of those the Classic guys will have it in their build. 

If I were you I'd get in touch with the Classic guys and see if they can get you a custom build. If you volunteered to test the change with a selection of games, for the benefit of the community, that might help grease the wheels into motion.

**Comment by gameblabla** [comment] 2019-03-07 19:42
I guess this could at least be implemented as an optional setting like Parasite Eve's hack (Config.RCntFix) while we figure out the root cause of the issue.

**Comment by gameblabla** [comment] 2019-03-15 20:14
Well it got merged, which means that you would need to toggle the setting for Diablo if you want to have music. Not a proper fix but hopefully this will motivate someone else to do it for us... which will never happen but oh well. Close maybe ?

**Comment by notaz** [comment] 2019-03-16 23:43
I prefer to keep it open until there is a proper fix (even if it ends up being or forever).

**Comment by LodanZark** [comment] 2019-03-17 00:16
I experienced the same issue with "Dead or Alive", soon as I enter Start Menu, the cda track stops for no apparent reason, I'm wonder if it's related with same bug as diablo...

**Comment by UristUriston** [comment] 2019-03-18 12:15
I just downloaded the latest km_PCSX ReARMed Neon Xtreme update where the hack has been implemented. It works like a charm and I just wanted to thank everybody involved. Never thought that I would see a solution to the problem when I was submitting the bug, but here it is just a few weeks later. I know it´s not a "proper" solution to the bug, but as a consumer I couldn`t be happier to just see it working. Being able to play this gem and show it to my buddies is great. Once again thanks for all your hard work, you guys are amazing!

**Comment by gingerbeardman** [comment] 2019-03-18 19:10
@UristUriston Thanks to you for taking the time to report it and feedback that it is working for you. That's the spirit of Open Source Software.

**Comment by rcaridade145** [comment] 2019-08-14 14:01
@gameblabla Have you taken a look at https://github.com/iCatButler/pcsxr/tree/master/plugins/dfsound ? That version seems to be more complete.

**Comment by gameblabla** [comment] 2019-08-14 19:11
@rcaridade145 I'm aware of PCSX-Reloaded commits. In fact this version is not the latest version of it, this is the one with additional commits (that were mostly merged for the most part) :
[https://github.com/gameblabla/pcsxr](https://github.com/gameblabla/pcsxr)

No fix for Diablo (although there is a hack fix for Toshin Subaru, maybe it could fix it but i have yet to give it a try).

**Comment by rcaridade145** [comment] 2019-08-15 11:06
@gameblabla Oh ok. I only mentioned it because browsing through the files related to dfsound there were some differences between this branch and that github and yours. And looking back at old post on ngemu [https://www.ngemu.com/threads/peops-dsound-1-09-repair.140191/page-29](https://www.ngemu.com/threads/peops-dsound-1-09-repair.140191/page-29) and such [https://www.emucr.com/2011/07/peops-dsound-psx-spu-v19a-r21.html](https://www.emucr.com/2011/07/peops-dsound-psx-spu-v19a-r21.html) about the work of developer by the name of shalma there is a mode called AsyncOndemand that solves most issues with sound

**Closed** 2021-08-22 21:50 UTC
