### ISSUE TITLE
Enhanced Resolution for 64-bit

### ISSUE THREAD

**Issue by ozgurkazancci** [notaz/pcsx_rearmed#265] opened 2022-09-17 23:20 UTC
Greetings.

Any plan to bring the "enhanced resolution" feature for 64-bit version of lr-pcsx-rearmed?

**Comment by notaz** [comment] 2022-09-18 18:02
Closing duplicate of libretro/pcsx_rearmed#690

**Closed by notaz** 2022-09-18 18:02 UTC
