### ISSUE TITLE
Loading ROM via -cdfile invocation doesn't load corresponding config file

### ISSUE THREAD

**Issue by porg** [notaz/pcsx_rearmed#282] opened 2023-01-15 18:47 UTC
## Environment
- PCSX ReARMed r23
- Device: OpenPandora
- OS: SuperZaxxon v1.76 update 3
- Launcher: Pandafe 0.3.0.2-b464

## Precondition
- ROM got customized display setting, was created via "Save cfg for loaded game" in menu.
- Is persisted in corresponding config file: `appdata/pcsx_rearmed/.pcsx/cfg/game-name-ID.cfg`

## Reproduction 1: Loading ROM via internal Menu loads corresponding config
1. Open PCSX ReARMed.
2. Press SPACE to open menu.
3. Choose "Load CD image".

→  ✅ PCSX loads the .CFG file corresponding to the chosen ROM.

## Reproduction 2: Loading ROM via -cdfile invocation doesn't load corresponding config
1. In Pandafe as the GUI launcher
2. Select a Playstation game and press game button "B" to launch it
   - Pandafe is [configured to launch pcsx](https://github.com/nuhrin/pandafe/blob/master/data/Program/pcsx_rearmed.notaz) with `-cdfile %g`
3. The game is launched successfully…

→ ❌ …but its corresponding .CGF file is not loaded.

## Expected / desired behavior
If `pcsx` is launched by external invocation (with `-cdfile /path/to/rom`):
1) by default loads the corresponding `.cfg` file from within the appdata `/cfg/` directory
   - Minimal fix which would guarantee individual game config overrides to also work with external launchers such as Pandafe.
2) for additional flexibility may offer overriding arguments:
  - a) `--config-dir /path/to/cgf-dir/ where is attempts to find a proper config file by name/ID match`
    - Possibility for a --config-dir per launcher (isolated from the main /cfg/ )
  - b) `--config-file /path/to/particular-rom-name.cfg`
    - That way you could create different customized launch configurations per game.

Note: I did not see any [pcsx command line argument](https://github.com/notaz/pcsx_rearmed/blob/d5aeda23720ba9374312f8d387f299024fedb7e6/maemo/main.c#L58) which would allow 2a or 2b.

**Comment by notaz** [comment] 2023-12-10 22:03
Duplicate of #163 and should be fixed now.

**Closed by notaz** 2023-12-10 22:03 UTC
