### ISSUE TITLE
Multiline cheats on RetroArch

### ISSUE THREAD

**Issue by uniQ168** [notaz/pcsx_rearmed#80] opened 2017-01-05 08:54 UTC
Hi,

I was just setting up a Raspberry Pi 3 with RetroPie 4.1 the other day and tried emulating PSX games with lr-pcsx-rearmed 25e52b2. I messed around with some gameshark cheats and it worked, but I can't seem to get multiline cheats working. Running the codes one by one is a bit of a clumsy process. ^^'
Am I doing something wrong?

This is working:
```
cheats = 2

cheat0_desc = "Infinite Ammo Claire (1/2)"
cheat0_code = "800D49F5+0063"
cheat0_enable = "true"

cheat1_desc = "Infinite Ammo Claire (2/2)"
cheat1_code = "800D4A01+0063"
cheat1_enable = "true"
```

This is not:
```
cheats = 1

cheat0_desc = "Infinite Ammo Claire"
cheat0_code = "800D49F5+0063+800D4A01+0063"
cheat0_enable = "true"
```

**Comment by uniQ168** [comment] 2017-01-09 07:55
Nobody? ^^' Or is this project dead?

**Comment by notaz** [comment] 2017-01-09 10:24
Sort of :(
I still keep the bug list in case I can take it sometime (if ever), but that's not going to happen in immediate future.

**Comment by uniQ168** [comment] 2017-01-10 12:51
Sad to hear but understandable, since free time is precious these days. :)

**Comment by notaz** [comment] 2023-09-28 22:47
Duplicate of libretro/pcsx_rearmed#90

**Closed by notaz** 2023-09-28 22:47 UTC
